on:
  pull_request:
  push:
   branches:
     - main
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build-sample-project:
    name: Build sample project
    strategy:
      matrix:
        system:
          - macos-latest
          - ubuntu-latest
          # - windows-latest # for some reason windows build is not picking dune 3.5
        ocaml-compiler:
          - 4.14.x

      fail-fast: false
    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install all deps
        run: make install

      - name: Build basic template
        run: opam exec -- mel

      - name: Bundle JS app
        run: npm run bundle

      - name: Run resulting .js files
        run: |
          node _build/default/src/Hello.bs.js
          node _build/default/src/Main.bs.js
